// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCQVDzyxoFY-h_Sh1upKzPWOxmozMuBMiA',
    appId: '1:968403569191:web:cb742c30246196aaff1c02',
    messagingSenderId: '968403569191',
    projectId: 'shopapp-c0f01',
    authDomain: 'shopapp-c0f01.firebaseapp.com',
    storageBucket: 'shopapp-c0f01.firebasestorage.app',
    measurementId: 'G-X7Z4K4H6K2',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAo_0S-nrbmXxn3h9s16I7v-_hN49vRyOg',
    appId: '1:968403569191:android:12b78aa6ae15a07dff1c02',
    messagingSenderId: '968403569191',
    projectId: 'shopapp-c0f01',
    storageBucket: 'shopapp-c0f01.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCorijLyY2jZDSEzYyTZfCY3R1jvZ_kfdM',
    appId: '1:968403569191:ios:410383b4e60a202fff1c02',
    messagingSenderId: '968403569191',
    projectId: 'shopapp-c0f01',
    storageBucket: 'shopapp-c0f01.firebasestorage.app',
    iosBundleId: 'com.example.firebaseApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCorijLyY2jZDSEzYyTZfCY3R1jvZ_kfdM',
    appId: '1:968403569191:ios:410383b4e60a202fff1c02',
    messagingSenderId: '968403569191',
    projectId: 'shopapp-c0f01',
    storageBucket: 'shopapp-c0f01.firebasestorage.app',
    iosBundleId: 'com.example.firebaseApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCQVDzyxoFY-h_Sh1upKzPWOxmozMuBMiA',
    appId: '1:968403569191:web:21bb02f156869b7eff1c02',
    messagingSenderId: '968403569191',
    projectId: 'shopapp-c0f01',
    authDomain: 'shopapp-c0f01.firebaseapp.com',
    storageBucket: 'shopapp-c0f01.firebasestorage.app',
    measurementId: 'G-VJFZ2MCBWM',
  );
}
